#%RAML 1.0 ResourceType
post:
  description: <<resource PathName>> resource created 
  responses:    
    201:
      body:
        application/json:
          example: <<exampleReference>>
          

             