#%RAML 1.0
title: DeliveryAppGroupB

/Amdin:
  post:
    body:      
      application/json:
        example: !include EXAMPLES/ADMINexample.raml

          
    responses:
      201:
        body:
          application/json:
            example: 
             
                {
                  msg: "Account successfully created!"
                }                                    
            
                
                
                
      400:
        body:
          application/json:
            example:
              {
                msg: "Bad request"
              }
      500:
        body:
          application/json:
            example:
              {
                msg: "server error"
              }
  get:
    responses:
      201:
        body:
          application/json:
            example: !include EXAMPLES/ADMINGET_PUT_dELETE_example.raml

      404:
        body:
          application/json:
            example:
              {
                msg: "Not Found"
              }
  put:
    body:
      application/json:
        example: !include EXAMPLES/ADMINGET_PUT_dELETE_example.raml

    responses:
      201:
        body:
          application/json:
            example:
              {
                msg: "succesfully Edited"
              }
      405:
        body:
          application/json:
            example:
              {
                msg: "Not allowed"
              }
      500:
        body:
          application/json:
            example:
              {
                msg: "server error"
              }
  


      
  delete:
    body:
      application/json: 
        example: !include EXAMPLES/ADMINGET_PUT_dELETE_example.raml
  
    responses:
      200:
        body:
          application/json:
            example:
              {
                msg: "Successfully deleted"
              }
      404:
        body:
          application/json:
            example:
              {
                "Not Found"
              }           

        


/Customer:
  post:
    body:
      application/json:
        example:
          {
            "Name": "Abebe beso bela", 
            "Address": "123 abc white house",
            "Email": "Abebe_Bela@Ethio.com",
            "Phone Number": 025568478
            
          }
    responses:
      201:
        body:
          application/json:
            example:
              {
                "UserId": 001                
              }
      500:
        body:
          application/json:
            example:
              {
                msg: "Server Error"
              }
  get:
    queryParameters: 
      username: 
        type: string 
      password:
        type: string
    responses:
      200:
        body:
          application/json:
            example:
              {
                msg: "Succefully Logged in "
              }
      404:
        body:
          application/json:
            example:
              {
                msg: "Not Found"
              }
      500:
        body:
          application/json:
            example:
              {
                msg: "Server Error"
              }    

/Delivery Man:
  get:
    description: Delivery Man getting cutstomer Info
    responses:
      200:
        body:
          application/json:
            example: !

              

      404:
        body:
          application/json:
            example:
              {
                msg: "Not found"
              }

        


    

