#%RAML 1.0
title: DeliveryAppGroupB

/Amdin:
  post:
    body:      
      application/json:
        example:
          [{
        "id": 100,
        "customer_id": 22,
        "driver_id": 403,
        "unit_price": 411.0,
        },
        {
        "id": 101,  
        "customer_id": 23,
        "driver_id": 403,
        "unit_price": 855.0
          }
          ]
          
    responses:
      201:
        body:
          application/json:
            example: 
            type: 

              {
                msg: "Account successfully created!"
              }
      400:
        body:
          application/json:
            example:
              exampleReference:
                {
                msg: "Bad request"
                }
      500:
        body:
          application/json:
            example:
              {
                msg: "server error"
              }
  get:
    responses:
      201:
        body:
          application/json:
            example:
              {
              "id": 101,  
              "customer_id": 23,
              "driver_id": 403,
              "unit_price": 855.0
              }
      404:
        body:
          application/json:
            example:
              {
                msg: "Not Found"
              }
  put:
    body:
      application/json:
        example:
          {
            "id": 101,  
              "customer_id": 23,
              "driver_id": 403,
              "unit_price": 855.0
          }
    responses:
      201:
        body:
          application/json:
            example:
              {
                msg: "succesfully Edited"
              }
      405:
        body:
          application/json:
            example:
              {
                msg: "Not allowed"
              }
      500:
        body:
          application/json:
            example:
              {
                msg: "server error"
              }
  


      
  delete:
    body:
      application/json: 
        example:
          {
            "id": 101,  
            "customer_id": 23,
            "driver_id": 403,
            "unit_price": 855.0
          }
    responses:
      200:
        body:
          application/json:
            example:
              {
                msg: "Successfully deleted"
              }
      404:
        body:
          application/json:
            example:
              {
                "Not Found"
              }           

        


/Customer:
  post:
    body:
      application/json:
        example:
          {
            "Name": "Abebe beso bela", 
            "Address": "123 abc white house",
            "Email": "Abebe_Bela@Ethio.com",
            "Phone Number": 025568478
            
          }
    responses:
      201:
        body:
          application/json:
            example:
              {
                "UserId": 001                
              }
      500:
        body:
          application/json:
            example:
              {
                msg: "Server Error"
              }
  get:
    queryParameters: 
      username: 
        type: string 
      password:
        type: string
    responses:
      200:
        body:
          application/json:
            example:
              {
                msg: "Succefully Logged in "
              }
      404:
        body:
          application/json:
            example:
              {
                msg: "Not Found"
              }
      500:
        body:
          application/json:
            example:
              {
                msg: "Server Error"
              }    

/Delivery Man:
  get:
    description: Delivery Man getting cutstomer Info
    responses:
      200:
        body:
          application/json:
            example:
              {
                "Name": "Yidnekachew Maru",
                "Location": "GroupB",
                "Phone number": 2469780561           
              }
      404:
        body:
          application/json:
            example:
              {
                msg: "Not found"
              }

        


    

