#%RAML 1.0
title: DeliveryAppGroupB
types:
  Admin: !include Data Type/AdmindataType.raml
  Customer: !include Data Type/CustomerdataType.raml
  DeliveryMan: !include Data Type/DeliveryMandataType.raml
traits:
  Errors: !include Traits/ErrorResponces.raml 


/Amdin:
  post:
    body:      
      application/json:
        example: !include EXAMPLES/ADMINexample.raml

          
    responses:
      201:
        body:
          application/json:
            example: 
             
                {
                  msg: "Account successfully created!"
                }                                   
    is:
      - Errors
                
                
                

  get:
    responses:
      201:
        body:
          application/json:
            example: !include EXAMPLES/ADMINGET_PUT_dELETE_example.raml

      404:
        body:
          application/json:
            example:
              {
                msg: "Not Found"
              }
  put:
    body:
      application/json:
        example: !include EXAMPLES/ADMINGET_PUT_dELETE_example.raml

    responses:
      201:
        body:
          application/json:
            example:
              {
                msg: "succesfully Edited"
              }

    is:
      - Errors



      
  delete:
    body:
      application/json: 
        example: !include EXAMPLES/ADMINGET_PUT_dELETE_example.raml
  
    responses:
      200:
        body:
          application/json:
            example:
              {
                msg: "Successfully deleted"
              }
    is:
      Errors

               

        


/Customer:
  post:
    body:
      application/json:
        example: !include EXAMPLES/Customerexample.raml

    responses:
      201:
        body:
          application/json:
            example:
              {
                "UserId": 001                
              }
      500:
        body:
          application/json:
            example:
              {
                msg: "Server Error"
              }
  get:
    queryParameters: 
      username: 
        type: string 
      password:
        type: string
    responses:
      200:
        body:
          application/json:
            example:
              {
                msg: "Succefully Logged in "
              }


    is:
      - Errors
  

/Delivery Man:
  get:
    description: Delivery Man getting cutstomer Info
    responses:
      200:
        body:
          application/json:
            example: !include EXAMPLES/DeliveryManexample.raml

              

  is:
    - Errors
        


    

