#%RAML 1.0 DataType
type: 

  properties:
    id:
      type: integer
    customer_id:
      type: integer
    driver_id:
      type: integer
    

        #     "id": 100,
        # "": 22,
        # "driver_id": 403,
        # "unit_price": 411.0,






